package com.kgaft.SecureMessengerPCClient.UI.AuthorizationScreen;

import com.kgaft.SecureMessengerPCClient.BackEnd.AppProperties.AppProperties;
import com.kgaft.SecureMessengerPCClient.BackEnd.Authorization.AuthorizationNativeCalls;
import com.kgaft.SecureMessengerPCClient.BackEnd.CheckConnectionService.CheckConnectionService;
import com.kgaft.SecureMessengerPCClient.BackEnd.MessageService.MessageReceiverManager.MessageManager;
import com.kgaft.SecureMessengerPCClient.BackEnd.MessageService.MessageReceiverService;
import com.kgaft.SecureMessengerPCClient.BackEnd.ServiceHandler;
import com.kgaft.SecureMessengerPCClient.UI.MainScreen.MainScreen;
import com.kgaft.SecureMessengerPCClient.UI.ScreenInterface;
import com.kgaft.SecureMessengerPCClient.UI.ScreenManager;

import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.lang.reflect.InvocationTargetException;
import java.sql.SQLException;
import java.util.Locale;

public class RegistrationScreen extends JFrame implements ScreenInterface {
    private JLabel messengerName;
    private JTextField serverAddressInput;
    private JTextField loginInput;
    private JPasswordField passwordInput;
    private JButton registrationButton;
    private JTextField nameInput;
    private JPasswordField passwordRepeatInput;
    private JButton loginButton;
    private JPanel root;
    private JLabel errorLable;

    public RegistrationScreen() {
        setContentPane(root);
        setTitle("Authorization Screen");
        setSize(500, 500);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        initRegistrationButton();
        initLoginButton();
    }

    private void initRegistrationButton() {
        registrationButton.addActionListener(event -> {
            errorLable.setText("");
            if (passwordInput.getText().equals(passwordRepeatInput.getText())) {
                AuthorizationNativeCalls server = new AuthorizationNativeCalls(serverAddressInput.getText());
                if (server.register(loginInput.getText(), passwordInput.getText(), nameInput.getText())) {
                    try {
                        AppProperties.setServerBaseUrl(serverAddressInput.getText());
                        ServiceHandler.insertService(new MessageReceiverService(new MessageManager(AppProperties.getServerBaseUrl()), new AuthorizationNativeCalls(AppProperties.getServerBaseUrl())));
                        initCheckConnectionService();
                        closeScreen();
                        showMainScreen();
                         ServiceHandler.start();
                    } catch (Exception e) {
                        initCheckConnectionService();
                        closeScreen();
                    }
                } else {
                    errorLable.setText("Error: registration failed!");
                }
            } else {
                errorLable.setText("Error: password didn't match");
            }
        });
    }

    private void initCheckConnectionService() {
        int checkConnectionServiceState = ServiceHandler.getServiceState(CheckConnectionService.class);
        if (checkConnectionServiceState == ServiceHandler.SERVICE_DOES_NOT_EXISTS) {
            try {
                ServiceHandler.insertService(new CheckConnectionService());
            } catch (SQLException e) {
                e.printStackTrace();
            } catch (InvocationTargetException e) {
                e.printStackTrace();
            } catch (NoSuchMethodException e) {
                e.printStackTrace();
            } catch (InstantiationException e) {
                e.printStackTrace();
            } catch (IllegalAccessException e) {
                e.printStackTrace();
            }
        }
        ServiceHandler.start();

    }

    private void showMainScreen() {
        ScreenManager.getAllScreens().forEach(screen -> {
            if (screen.getClass() == MainScreen.class) {
                screen.showScreen();

            }
        });
    }

    private void initLoginButton() {
        loginButton.addActionListener(event -> {
            ScreenManager.getAllScreens().forEach(screen -> {
                if (screen.getClass() == LoginScreen.class) {
                    screen.showScreen();
                }
            });
            hideScreen();
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        root = new JPanel();
        root.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(9, 3, new Insets(0, 100, 0, 100), -1, -1));
        messengerName = new JLabel();
        Font messengerNameFont = this.$$$getFont$$$(null, -1, 20, messengerName.getFont());
        if (messengerNameFont != null) messengerName.setFont(messengerNameFont);
        messengerName.setHorizontalAlignment(0);
        messengerName.setHorizontalTextPosition(0);
        messengerName.setText("SecureMessenger");
        root.add(messengerName, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        serverAddressInput = new JTextField();
        serverAddressInput.setDisabledTextColor(new Color(-6273105));
        serverAddressInput.setSelectionColor(new Color(-6273105));
        serverAddressInput.setText("Server address");
        root.add(serverAddressInput, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        loginInput = new JTextField();
        loginInput.setSelectionColor(new Color(-6273105));
        loginInput.setText("Login");
        loginInput.setToolTipText("");
        root.add(loginInput, new com.intellij.uiDesigner.core.GridConstraints(4, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        passwordInput = new JPasswordField();
        passwordInput.setSelectionColor(new Color(-6273105));
        passwordInput.setText("Password");
        passwordInput.setToolTipText("");
        root.add(passwordInput, new com.intellij.uiDesigner.core.GridConstraints(5, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        registrationButton = new JButton();
        registrationButton.setText("Registration");
        root.add(registrationButton, new com.intellij.uiDesigner.core.GridConstraints(7, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        nameInput = new JTextField();
        nameInput.setText("Name");
        root.add(nameInput, new com.intellij.uiDesigner.core.GridConstraints(3, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        passwordRepeatInput = new JPasswordField();
        passwordRepeatInput.setText("password");
        root.add(passwordRepeatInput, new com.intellij.uiDesigner.core.GridConstraints(6, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        loginButton = new JButton();
        loginButton.setText("Login");
        root.add(loginButton, new com.intellij.uiDesigner.core.GridConstraints(8, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        errorLable = new JLabel();
        errorLable.setText("");
        root.add(errorLable, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return root;
    }

    @Override
    public void showScreen() {
        setVisible(true);
    }

    @Override
    public void hideScreen() {
        setVisible(false);
    }

    @Override
    public void closeScreen() {
        hideScreen();
        dispose();
    }
}
